# Generated by Django 5.2.17 on 2026-09-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='typesafe_api_key',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
